consumer:
  name: search-svc
  consumed_contract_path: /fixtures-poly/consumers/search-svc/consumed-contract.json
  operations:
    - path: /items
      method: get
provider:
  name: catalog
  spec_path: /fixtures-poly/providers/catalog/v1.yaml
settings:
  save_json_report: false
  timeout: 5
